baseURL = "https://www.paketo.io/"
title = "Paketo Buildpacks"

pygmentsUseClasses = true
pygmentsCodefences = true

[params.hero]
  headline = "Paketo Buildpacks"
  subheadline = "Less time building, more time developing"
  subhead = "Java, Node.js, Go, .NET Core, PHP, NGINX"

  cta_text = "Read the announcement"
  cta_link = "https://medium.com/paketo-buildpacks"

[params.what_are_buildpacks]
  headline = "What are Buildpacks?"
  description = "Buildpacks are a CNCF project that provide a high-level, performant abstraction for building OCI app images."
  cta_text = "More about the Buildpacks Project"
  cta_link = "https://buildpacks.io"

[params.what_are_paketo_buildpacks]
  headline = "What are Paketo Buildpacks?"
  description = "Paketo Buildpacks provide modular language runtime support for applications while leveraging standards in the Cloud Native Buildpacks specification to make image builds performant and secure."

  [[params.what_are_paketo_buildpacks.item]]
    name = "Node.js"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "npm"
    elem_link = "github.com/paketo-buildpacks/npm"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "yarn"
    elem_link = "github.com/paketo-buildpacks/yarn"

  [[params.what_are_paketo_buildpacks.item]]
    name = "Java"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "jmx"
    elem_link = "github.com/paketo-buildpacks/jmx"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "google-stackdriver"
    elem_link = "github.com/paketo-buildpacks/google-stackdriver"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "eclipse-openj9"
    elem_link = "github.com/paketo-buildpacks/eclipse-openj9"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "build-system"
    elem_link = "github.com/paketo-buildpacks/build-system"

  [[params.what_are_paketo_buildpacks.item]]
    name = "Go"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "go-compiler"
    elem_link = "github.com/paketo-buildpacks/go-compiler"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dep"
    elem_link = "github.com/paketo-buildpacks/dep"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "go-mod"
    elem_link = "github.com/paketo-buildpacks/go-mod"

  [[params.what_are_paketo_buildpacks.item]]
    name = ".NET Core"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-runtime"
    elem_link = "github.com/paketo-buildpacks/dotnet-core-runtime"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-aspnet"
    elem_link = "github.com/paketo-buildpacks/dotnet-core-aspnet"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-sdk"
    elem_link = "github.com/paketo-buildpacks/dotnet-core-sdk"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-build"
    elem_link = "github.com/paketo-buildpacks/dotnet-core-build"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-conf"
    elem_link = "github.com/paketo-buildpacks/dotnet-core-conf"

  [[params.what_are_paketo_buildpacks.item]]
    name = "PHP"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-dist"
    elem_link = "github.com/paketo-buildpacks/php-dist"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-web"
    elem_link = "github.com/paketo-buildpacks/php-web"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-composer"
    elem_link = "github.com/paketo-buildpacks/php-composer"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "httpd"
    elem_link = "github.com/paketo-buildpacks/httpd"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "nginx"
    elem_link = "github.com/paketo-buildpacks/nginx"

[params.why_paketo]
    headline = "Why Paketo Buildpacks?"
    copy = ""

  [[params.why_paketo.item]]
    title = "Quality"
    description = "The Paketo project is built on over five years of feeback from hundreds of thousands of developer."

  [[params.why_paketo.item]]
    title = "Security"
    description = "The Paketo project ensures that upstream languages, runtimes and frameworks are continuiously patched in response to vulnerabilities and updates."

  [[params.why_paketo.item]]
    title = "Community"
    description = "The Paketo project is a open source project, all major decisions are made by the RFC process"

  [[params.why_paketo.item]]
    title = "Industry standard"
    description = "Paketo buildpacks are compliant with the latest version of the CNB specification."


[params.faq]
  headline = "FAQ"

  [[params.faq.item]]
    q = "How are Paketo Buildpacks different from Cloud Foundry Buildpacks?"
    a = "Cloud Foundry Buildpacks have been restructured so they can be used in any cloud native environment. As such, they are now called Paketo Buildpacks. Paketo Buildpacks are CNB compliant -- the legacy Cloud Foundry Buildpacks are not."

  [[params.faq.item]]
    q = "How are Paketo Buildpacks different from the Cloud Native Buildpack project?"
    a = "Cloud Native Buildpacks (CNB) is a specification and set of tools for how buildpacks are structured. Paketo buildpacks implement that specification into a collection of usable buildpacks. Learn more at <a class='cta' href='buildpacks.io'>buildpacks.io</a>."

  [[params.faq.item]]
    q = "What if I’m using Cloud Foundry Buildpacks? How do I make the change to Paketo Buildpacks?"
    a = "The Cloud Foundry Buildpacks team is already working on Paketo Buildpacks and will ensure a smooth transition for developers using Cloud Foundry Buildpacks."

  [[params.faq.item]]
    q = "What languages and frameworks can I use with Paketo Buildpacks?"
    a = "At launch, Paketo Buildpacks will officially support the Java and NodeJS Paketo Buildpacks as well as tools/libraries that allow you to build and test your own Paketo Buildpacks. The team is also actively developing .Net, PHP, Golang, and Python Paketo Buildpacks."

  [[params.faq.item]]
    q = "How do I contribute to Paketo Buildpacks?"
    a = "Join the Paketo Buildpacks working group meetings to introduce yourself and hear about what’s in flight."
  
[params.get_started]
  headline = "Get Started with Paketo Buildpacks"

  [[params.get_started.item]]
    icon = "paketo-documentation.svg"
    text = "Documentation"
    link = "#"

  [[params.get_started.item]]
    icon = "paketo-tutorial.svg"
    text = "Tutorial"
    link = "#"

