baseURL = "https://paketo.io/"
title = "Paketo Buildpacks"

pygmentsUseClasses = true
pygmentsCodefences = true

# path name excluded from documentation menu
menu_exclusion = [
    "faq",
    "docs"
]

[params.hero]
    headline = "Paketo Buildpacks"
    subheadline = "build your apps into container images for the most popular languages"

    cta_text = "Get Started"
    cta_link = "/docs/"

    [[params.hero.logos]]
        [[params.hero.logos.item]]
            img = "java-logo.png"
            alt = "java logo"

        [[params.hero.logos.item]]
            img = "go-logo.png"
            alt = "go logo"

        [[params.hero.logos.item]]
            img = "net-core-logo.png"
            alt = ".net core logo"

        [[params.hero.logos.item]]
            img = "nginx-logo.png"
            alt = "nginx logo"

        [[params.hero.logos.item]]
            img = "node-logo.png"
            alt = "node logo"

        [[params.hero.logos.item]]
            img = "php-logo.png"
            alt = "php logo"

[params.what_are_buildpacks]
  headline = "What are Buildpacks?"
  description = "Buildpacks transform your application source code to image that can run on any cloud. Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure."
  cta_text = "More about the Cloud Native Buildpacks project"
  cta_link = "https://buildpacks.io"

[params.language_packages]
  [[params.language_packages.item]]
    name = "Node.js"

    [[params.language_packages.item.subitem]]
    elem_name = "Node.js"
    elem_link = "https://github.com/paketo-buildpacks/nodejs"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Node Engine"
    elem_link = "https://github.com/paketo-buildpacks/node-engine"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ NPM"
    elem_link = "https://github.com/paketo-buildpacks/npm"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Yarn"
    elem_link = "https://github.com/paketo-buildpacks/yarn-install"

  [[params.language_packages.item]]
    name = "Java"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Adopt-openjdk"
      elem_link = "https://github.com/paketo-buildpacks/adopt-openjdk"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Build-system"
      elem_link = "https://github.com/paketo-buildpacks/build-system"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Apache-tomcat"
      elem_link = "https://github.com/paketo-buildpacks/apache-tomcat"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Spring-boot"
      elem_link = "https://github.com/paketo-buildpacks/spring-boot"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Dist-zip"
      elem_link = "https://github.com/paketo-buildpacks/dist-zip"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Procfile"
      elem_link = "https://github.com/paketo-buildpacks/procfile"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Azure-application-insights"
      elem_link = "https://github.com/paketo-buildpacks/azure-application-insights"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Debug"
      elem_link = "https://github.com/paketo-buildpacks/debug"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Googlestackdriver"
      elem_link = "https://github.com/paketo-buildpacks/google-stackdriver"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ JMX"
      elem_link = "https://github.com/paketo-buildpacks/jmx"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Executable-jar"
      elem_link = "https://github.com/paketo-buildpacks/executable-jar"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Eclipse-open9"
      elem_link = "https://github.com/paketo-buildpacks/eclipse-openj9"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Sap-machine"
      elem_link = "https://github.com/paketo-buildpacks/sap-machine"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Adopt-openjdk"
      elem_link = "https://github.com/paketo-buildpacks/adopt-openjdk"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Bellsoft-liberica"
      elem_link = "https://github.com/paketo-buildpacks/bellsoft-liberica"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Encrypt-at-rest"
      elem_link = "https://github.com/paketo-buildpacks/encrypt-at-rest"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Azul-zulu"
      elem_link = "https://github.com/paketo-buildpacks/azul-zulu"

    [[params.language_packages.item.subitem]]
      elem_name = "↳ Amazon-corretto"
      elem_link = "https://github.com/paketo-buildpacks/amazon-corretto"

  [[params.language_packages.item]]
    name = "Go"

    [[params.language_packages.item.subitem]]
    elem_name = "Go"
    elem_link = "https://github.com/paketo-buildpacks/go"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Compiler"
    elem_link = "https://github.com/paketo-buildpacks/go-compiler"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Dep"
    elem_link = "https://github.com/paketo-buildpacks/dep"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Modules"
    elem_link = "https://github.com/paketo-buildpacks/go-mod"

  [[params.language_packages.item]]
    name = ".NET Core"

    [[params.language_packages.item.subitem]]
    elem_name = ".NET Core"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Runtime"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ ASP.NET Core"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ SDK"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Source Build"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-build"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Configuration"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-conf"

  [[params.language_packages.item]]
    name = "PHP"

    [[params.language_packages.item.subitem]]
    elem_name = "PHP"
    elem_link = "https://github.com/paketo-buildpacks/php"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Distribution"
    elem_link = "https://github.com/paketo-buildpacks/php-dist"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Web"
    elem_link = "https://github.com/paketo-buildpacks/php-web"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ Composer"
    elem_link = "https://github.com/paketo-buildpacks/php-composer"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ HTTPD"
    elem_link = "https://github.com/paketo-buildpacks/httpd"

    [[params.language_packages.item.subitem]]
    elem_name = "↳ NGINX"
    elem_link = "https://github.com/paketo-buildpacks/nginx"

[params.why_paketo]
    headline = "Why Paketo Buildpacks?"
    copy = ""

  [[params.why_paketo.item]]
    title = "Secure"
    description = "The Paketo project ensures that upstream languages, runtimes, and frameworks are continuously patched in response to vulnerabilities and updates."
    image = "images/REPLACE_ME.png"

  [[params.why_paketo.item]]
    title = "Standardized"
    description = "Paketo Buildpacks implement the Cloud Native Buildpacks specification, an emerging standard for building app container images. You can use Paketo Buildpacks with tools such as the CNB pack CLI, kpack, Tekton, and Skaffold, in addition to a number of cloud platforms. The Paketo project is built on over five years of feedback from hundreds of thousands of developers using Cloud Foundry Buildpacks. Unlike past generations of buildpacks, Paketo Buildpacks are modular, transparent, and written in Go."
    image = "images/REPLACE_ME.png"
    reverse_class = "reverse"

  [[params.why_paketo.item]]
    title = "Community-Driven"
    description = "The Paketo Buildpacks project lives within the Cloud Foundry Foundation and is dedicated to maintaining a vendor-neutral governance process."
    image = "images/REPLACE_ME.png"

[params.get_started]
  headline = "Getting Started"

  [[params.get_started.item]]
    icon = "paketo-tutorial.svg"
    text = "Tutorial"
    link = "https://medium.com/paketo-buildpacks/building-apps-for-kubernetes-get-to-know-paketo-buildpacks-6dc29b0f3cf3"

  [[params.get_started.item]]
    icon = "paketo-documentation.svg"
    text = "Docs"
    link = "/docs/"
