baseURL = "https://paketo.io/"
title = "Paketo Buildpacks"

pygmentsUseClasses = true
pygmentsCodefences = true

# path name excluded from documentation menu
menu_exclusion = [
    "faq",
    "docs"
]

[params.hero]
    headline = "Paketo Buildpacks"
    subheadline = "Less time building, more time developing"

    cta_text = "Read the announcement"
    cta_link = "https://medium.com/paketo-buildpacks"

    [[params.hero.logos]]
        [[params.hero.logos.item]]
            img = "java-logo.png"
            alt = "java logo"

        [[params.hero.logos.item]]
            img = "go-logo.png"
            alt = "go logo"

        [[params.hero.logos.item]]
            img = "net-core-logo.png"
            alt = ".net core logo"

        [[params.hero.logos.item]]
            img = "nginx-logo.png"
            alt = "nginx logo"

        [[params.hero.logos.item]]
            img = "node-logo.png"
            alt = "node logo"

        [[params.hero.logos.item]]
            img = "php-logo.png"
            alt = "php logo"

[params.what_are_buildpacks]
  headline = "What are Buildpacks?"
  description = "Cloud Native Buildpacks is a Sandbox project in the Cloud Native Computing Foundation (CNCF) that provides a high-level, performant abstraction for building container images. Cloud Native Buildpacks is an evolution of the buildpacks concept that originated with PaaS like Cloud Foundry."
  cta_text = "More about the Cloud Native Buildpacks project"
  cta_link = "https://buildpacks.io"

[params.what_are_paketo_buildpacks]
  headline = "What are Paketo Buildpacks?"
  description = "Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure."

  [[params.what_are_paketo_buildpacks.item]]
    name = "Node.js"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "Node.js"
    elem_link = "https://github.com/paketo-buildpacks/nodejs"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "↳ Node Engine"
    elem_link = "https://github.com/paketo-buildpacks/node-engine"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "↳ NPM"
    elem_link = "https://github.com/paketo-buildpacks/npm"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "↳ Yarn"
    elem_link = "https://github.com/paketo-buildpacks/yarn-install"

  [[params.what_are_paketo_buildpacks.item]]
    name = "Java"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "jmx"
    elem_link = "https://github.com/paketo-buildpacks/jmx"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "google-stackdriver"
    elem_link = "https://github.com/paketo-buildpacks/google-stackdriver"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "eclipse-openj9"
    elem_link = "https://github.com/paketo-buildpacks/eclipse-openj9"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "build-system"
    elem_link = "https://github.com/paketo-buildpacks/build-system"

  [[params.what_are_paketo_buildpacks.item]]
    name = "Go"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "go-compiler"
    elem_link = "https://github.com/paketo-buildpacks/go-compiler"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dep"
    elem_link = "https://github.com/paketo-buildpacks/dep"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "go-mod"
    elem_link = "https://github.com/paketo-buildpacks/go-mod"

  [[params.what_are_paketo_buildpacks.item]]
    name = ".NET Core"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-runtime"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-runtime"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-aspnet"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-sdk"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-build"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-build"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "dotnet-core-conf"
    elem_link = "https://github.com/paketo-buildpacks/dotnet-core-conf"

  [[params.what_are_paketo_buildpacks.item]]
    name = "PHP"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-dist"
    elem_link = "https://github.com/paketo-buildpacks/php-dist"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-web"
    elem_link = "https://github.com/paketo-buildpacks/php-web"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "php-composer"
    elem_link = "https://github.com/paketo-buildpacks/php-composer"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "httpd"
    elem_link = "https://github.com/paketo-buildpacks/httpd"

    [[params.what_are_paketo_buildpacks.item.subitem]]
    elem_name = "nginx"
    elem_link = "https://github.com/paketo-buildpacks/nginx"

[params.why_paketo]
    headline = "Why Paketo Buildpacks?"
    copy = ""

  [[params.why_paketo.item]]
    title = "Quality"
    description = "The Paketo project is built on over five years of feedback from hundreds of thousands of developers using Cloud Foundry Buildpacks."

  [[params.why_paketo.item]]
    title = "Security"
    description = "The Paketo project ensures that upstream languages, runtimes, and frameworks are continuously patched in response to vulnerabilities and updates."

  [[params.why_paketo.item]]
    title = "Community"
    description = "The Paketo Buildpacks project lives within the Cloud Foundry Foundation and is dedicated to maintaining a vendor-neutral governance process."

  [[params.why_paketo.item]]
    title = "Standard"
    description = "Paketo buildpacks are compliant with the latest version of the Cloud Native Buildpacks specification."

  
[params.get_started]
  headline = "Getting Started"

  [[params.get_started.item]]
    icon = "paketo-tutorial.svg"
    text = "Tutorial"
    link = "/docs/getting-started"

  [[params.get_started.item]]
    icon = "paketo-documentation.svg"
    text = "Docs"
    link = "/docs/"

