name: Deploy PR to Firebase

on:
  pull_request:
    types:
      - synchronize # new commits pushed, hopefully this covers 'opened' too.
  workflow_dispatch: {}

jobs:
  deploy-dev-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        check-latest: true
    - uses: actions/checkout@v1
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.84.0'
        extended: true

    - name: Install node Modules
      run: npm install

    - name: Disable Crawling on staging site
      run: |
        printf "User-agent: *\nDissallow: /\n" > layouts/robots.txt

    - name: Build
      run: hugo

    - name: Deploy
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        script: |
            const deploy = require('./deploy.js')
            await deploy({ context, github })
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
